// @ts-check

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  systemDesignSidebar: [{ type: 'autogenerated', dirName: 'system-design' }],
  dotnetSidebar: [{ type: 'autogenerated', dirName: 'dotnet' }],
  pythonSidebar: [{ type: 'autogenerated', dirName: 'python' }],
  aiSidebar: [{ type: 'autogenerated', dirName: 'ai' }],
  awsSidebar: [{ type: 'autogenerated', dirName: 'aws' }],
  azureSidebar: [{ type: 'autogenerated', dirName: 'azure' }],
  databaseSidebar: [{ type: 'autogenerated', dirName: 'database' }],
  devopsSidebar: [{ type: 'autogenerated', dirName: 'devops' }],
  projectsSidebar: [{ type: 'autogenerated', dirName: 'projects' }],
  refsSidebar: [{ type: 'autogenerated', dirName: 'references' }],
};

export default sidebars;
